export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAIL = 'CART_ADD_FAIL'

export const CART_CHANGE_QTY = 'CART_CHANGE_QTY'
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM'

export const CART_CLEAR = 'CART_CLEAR'